DROP DATABASE IF EXISTS SERVICEITEMS;

CREATE DATABASE SERVICEITEMS;

USE SERVICEITEMS;

CREATE TABLE Provider(
	 id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 name VARCHAR(256) NOT NULL,
	 address VARCHAR(256) NOT NULL,
	 email VARCHAR(256) NOT NULL,
	 phone INT NOT NULL
 );


CREATE TABLE Customer(
	 id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 name VARCHAR(256) NOT NULL,
	 email VARCHAR(256) NOT NULL,
	 phone INT NOT NULL
);

CREATE TABLE SERVICEITEM(
	 id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 providerId INT UNSIGNED NOT NULL,
	 FOREIGN KEY (providerId) REFERENCES Provider(id)
	 name VARCHAR(256) NOT NULL,
	 description VARCHAR(256) NOT NULL,
	 categoryId INT UNSIGNED NOT NULL,
	 FOREIGN KEY (categoryId) REFERENCES Category(id)
	 price VARCHAR(256) NOT NULL,
);

CREATE TABLE Category(
	 id INT UNSIGNED NOT NULL,
	 subcategory VARCHAR(256)
);


INSERT INTO Provider (name, address, email, phone)
	VALUES("Michelle", "CMC Stark Hall 600", "xsun17@cmc.edu", "9097891234");
